import Head from 'next/head'
import CategoryList from '../components/categories/CategoryList'
import SectionTitle from '../components/common/SectionTitle'
import Hero from '../components/home/Hero'
import NewsLetter from '../components/home/NewsLetter'
import ProductList from '../components/products/ProductList'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>

        <Hero />

        <SectionTitle>
          Latest Products
        </SectionTitle>
        <ProductList />

        <SectionTitle>
          Trending Categories
        </SectionTitle>
        <CategoryList />

        <NewsLetter />

      </main>
    </div>
  )
}
